version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - mongodb
    networks:
      - nxt-network
    restart: unless-stopped

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - nxt-network
    restart: unless-stopped

networks:
  nxt-network:
    driver: bridge

volumes:
  mongodb_data: